### ISSUE TITLE
Graphing doesn't account for the year

### ISSUE THREAD

**Issue by rhyzue** [rhyzue/KettleLog#29]
Maybe not worth fixing? After implementing reorder point, user might not be able to skip such a long time period without logging. 

<img width="1280" alt="Screen Shot 2019-08-10 at 2 53 22 PM" src="https://user-images.githubusercontent.com/45550256/62825766-dd06e200-bb7e-11e9-833d-f70de6cece11.png">

**Comment by Fraisin** [comment]
**Proposed Solution**
- Check the year of the log and store it before we convert it to MM/DD
- If the year is equal to our current year, we graph it
- This will not work when it's January 1, XXXX and the user has logs from December 26th -> December 31st, XXXX - 1. 
- In this case, we need to ensure that the 26th -> 31st have years that are 1 LESS THAN THE CURRENT YEAR, if and only if today is January 1st of the current year or later.

**Comment by Fraisin** [comment]
Okay just thought of a much easier solution...
- Get the 7 days of the graph first
- Check if any logs correspond to these dates
